import "./globals.css";
import "remixicon/fonts/remixicon.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import { Content_provider } from "@/provider/layout_provider";
import { Header } from "@/component/header";
import { Redux_provider } from "@/provider/redux_provider";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Redux_provider>
          <div
            style={{
              background: "linear-gradient(to right,  #1565c0,#b92b27)",
            }}
            className="flex flex-col  h-screen "
          >
            <Header />
            <Content_provider>{children}</Content_provider>
          </div>
        </Redux_provider>
      </body>
    </html>
  );
}
